"""
Customer model.

The central entity the CRM revolves around — calls and follow-ups both
belong to a customer. `customer_code` and `phone` are both unique so the
same real-world customer can't be entered twice (see DATABASE RULES in
the Module 2 spec: "No duplicate customers", "Phone must be unique").
"""

from sqlalchemy import Index, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.session import Base
from app.models.base import BaseModel, SoftDeleteMixin
from app.models.enums import CustomerStatus, sa_enum


class Customer(Base, BaseModel, SoftDeleteMixin):
    """
    A customer that can be called and followed up with.

    Soft-delete is enabled: customers are referenced by `calls` and
    `follow_ups`, so removing one must not silently delete call history.
    Deleting a customer through the app sets `is_deleted=True` instead of
    issuing a DB-level DELETE.
    """

    __tablename__ = "customers"
    __table_args__ = (
        Index("ix_customers_full_name", "full_name"),
        Index("ix_customers_city_state", "city", "state"),
    )

    # Human-friendly unique identifier (e.g. "CUST-00001"), generated by
    # the application/service layer in a later module — this column just
    # enforces uniqueness at the database level.
    customer_code: Mapped[str] = mapped_column(
        String(50), unique=True, index=True, nullable=False
    )

    full_name: Mapped[str] = mapped_column(String(150), nullable=False)

    phone: Mapped[str] = mapped_column(
        String(20), unique=True, index=True, nullable=False
    )

    email: Mapped[str | None] = mapped_column(String(255), nullable=True)

    company: Mapped[str | None] = mapped_column(String(150), nullable=True)

    city: Mapped[str | None] = mapped_column(String(100), nullable=True)

    state: Mapped[str | None] = mapped_column(String(100), nullable=True)

    # Added in Module 5 (Customer Management) — nullable so the Module 2
    # migration that created this table doesn't need to be rewritten;
    # a dedicated migration adds this column on top of it.
    country: Mapped[str | None] = mapped_column(String(100), nullable=True)

    notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    status: Mapped[CustomerStatus] = mapped_column(
        sa_enum(CustomerStatus),
        default=CustomerStatus.ACTIVE,
        nullable=False,
        index=True,
    )

    # A customer's calls and follow-ups are truly owned by that customer:
    # if a customer row is ever hard-deleted, its calls/follow-ups should
    # go with it (normal deletion in the app uses soft-delete instead —
    # see SoftDeleteMixin — so this cascade is a safety net, not the
    # primary deletion path).
    calls: Mapped[list["Call"]] = relationship(
        "Call",
        back_populates="customer",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )

    follow_ups: Mapped[list["FollowUp"]] = relationship(
        "FollowUp",
        back_populates="customer",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )

    def __repr__(self) -> str:  # pragma: no cover - debugging aid only
        return f"<Customer id={self.id} code={self.customer_code!r} phone={self.phone!r}>"
