"""
User model.

Represents an internal system user (admin, manager, or agent) who can
log in and operate the CRM. Authentication itself (password hashing,
login/signup endpoints, JWT issuing) is built in a later module — this
model only defines the storage shape.
"""

from sqlalchemy import String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.session import Base
from app.models.base import BaseModel, SoftDeleteMixin
from app.models.enums import UserRole, UserStatus, sa_enum


class User(Base, BaseModel, SoftDeleteMixin):
    """
    A CRM system user.

    Soft-delete is enabled because `reports.generated_by` and (in future
    modules) call ownership reference users — removing the row outright
    would break that history, so users are deactivated (`status`) or
    soft-deleted (`is_deleted`) instead of hard-deleted in normal use.
    """

    __tablename__ = "users"

    full_name: Mapped[str] = mapped_column(String(150), nullable=False)

    email: Mapped[str] = mapped_column(
        String(255), unique=True, index=True, nullable=False
    )

    password_hash: Mapped[str] = mapped_column(String(255), nullable=False)

    role: Mapped[UserRole] = mapped_column(
        sa_enum(UserRole),
        default=UserRole.AGENT,
        nullable=False,
        index=True,
    )

    status: Mapped[UserStatus] = mapped_column(
        sa_enum(UserStatus),
        default=UserStatus.ACTIVE,
        nullable=False,
        index=True,
    )

    # Reports generated by this user (see Report.generated_by).
    # `passive_deletes=True` lets the DB-level ON DELETE SET NULL (defined
    # on the FK in reports) do its job without SQLAlchemy issuing extra
    # UPDATE statements first.
    reports: Mapped[list["Report"]] = relationship(
        "Report",
        back_populates="generated_by_user",
        passive_deletes=True,
    )

    def __repr__(self) -> str:  # pragma: no cover - debugging aid only
        return f"<User id={self.id} email={self.email!r} role={self.role}>"
